initial commit
blueseaturtle/The-CRUD-Collection pull request #4
Opened 2022-10-03 19:48 UTC by nisalrenuja

2022-10-04 02:35 UTC, blueseaturtle commented
Thanks for your contribution!

Would you be able to add a small README file to the root of your `MERN_CRUD` folder describing what the project does, and how both the server and client can be run locally? It'll be very helpful.

Please let me know if you'll be able to ✌️

2022-10-04 04:31 UTC, nisalrenuja commented
sure I'll

2022-10-04 05:27 UTC, blueseaturtle requested changes
The commands needed to set up and run the project seem to be missing.
Something like [this](https://github.com/blueseaturtle/The-CRUD-Collection/tree/main/React_Redis/RhymePingPong#local-installation) would be great.

2022-10-05 02:01 UTC, blueseaturtle requested changes

2022-10-05 02:01 UTC, blueseaturtle commented on MERN/MERN_CRUD/README.md
> +5. Backend
Frontend

2022-10-05 02:01 UTC, blueseaturtle commented on MERN/MERN_CRUD/README.md
> +- Run cd server to enter the folder.
Run cd client .....

2022-10-05 02:01 UTC, blueseaturtle commented on MERN/MERN_CRUD/README.md
> +
Run npm start

2022-10-05 02:01 UTC, blueseaturtle commented on MERN/MERN_CRUD/README.md
> +
Add MongoDB Connection [Instructions](https://www.mongodb.com/docs/atlas/tutorial/connect-to-your-cluster/)

2022-10-05 02:01 UTC, blueseaturtle commented on MERN/MERN_CRUD/server.js
> +  "mongodb+srv://nisal:nisal@mernapp.wopdx.mongodb.net/mernCrud?retryWrites=true&w=majority";
Replace connection string with a place holder.
The use of a .env file would be good too I think, but will need instructions on how to set it up.

2024-06-02 14:11 UTC, closed without merging